"use client";
import { Place, Trip } from "../lib/types";

interface Props {
  tripName: string;
  places: Place[];
  days: number;
  style: Trip["style"];
  itinerary: string;
}

export default function ExportPDF({ tripName, places, days, style, itinerary }: Props) {
  function exportPDF() {
    const styleEmojis: Record<string, string> = {
      adventure: "🧗", relaxed: "🌴", cultural: "🏛️", budget: "💰",
    };

    const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>${tripName || "Trip Itinerary"}</title>
  <style>
    * { box-sizing: border-box; margin: 0; padding: 0; }
    body { font-family: 'Georgia', serif; color: #1e293b; padding: 48px; max-width: 720px; margin: 0 auto; }
    .header { border-bottom: 3px solid #7c3aed; padding-bottom: 20px; margin-bottom: 32px; }
    .title { font-size: 28px; font-weight: bold; color: #1e293b; }
    .meta { margin-top: 8px; font-size: 14px; color: #64748b; }
    .places { margin-top: 6px; font-size: 13px; color: #7c3aed; font-style: italic; }
    .itinerary { font-size: 15px; line-height: 1.8; white-space: pre-wrap; color: #334155; }
    .footer { margin-top: 48px; border-top: 1px solid #e2e8f0; padding-top: 16px; font-size: 12px; color: #94a3b8; text-align: center; }
    @media print { body { padding: 32px; } }
  </style>
</head>
<body>
  <div class="header">
    <div class="title">🧭 ${tripName || `${days}-Day Trip`}</div>
    <div class="meta">${styleEmojis[style]} ${style.charAt(0).toUpperCase() + style.slice(1)} &nbsp;·&nbsp; ${days} day${days > 1 ? "s" : ""}</div>
    <div class="places">📍 ${places.map(p => p.name).join(" → ")}</div>
  </div>
  <div class="itinerary">${itinerary.replace(/</g, "&lt;").replace(/>/g, "&gt;")}</div>
  <div class="footer">Generated by Smart Trip Planner · ${new Date().toLocaleDateString("en-US", { month: "long", day: "numeric", year: "numeric" })}</div>
</body>
</html>`;

    const blob = new Blob([html], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const win = window.open(url, "_blank");
    if (win) {
      win.onload = () => {
        win.print();
        URL.revokeObjectURL(url);
      };
    }
  }

  return (
    <button
      onClick={exportPDF}
      className="w-full mt-2 bg-slate-700 hover:bg-slate-600 text-slate-100 font-medium py-2.5 rounded-xl transition-all flex items-center justify-center gap-2 text-sm border border-slate-600"
    >
      📄 Export as PDF
    </button>
  );
}
